runner:
    lr: 1e-3
    optim: AdamW
    train_batch_size: 64
    valid_batch_size: 128
    shuffle: False
    multi_gpu: False
    device: cuda
    total_steps: 1000
    #world_size: 4
    num_workers: 0
    log_step: 100
    checkpoint_step: 100
    grad_clip: 1.0
    output_tb: False
    #start_from_ckpt: /storage/czw/self_supervised_seeg/outputs/2022-05-13/02-28-15/checkpoint_last.pth
    scheduler:
        name: reduce_on_plateau
        #name: ramp_up
        total_steps: ${exp.runner.total_steps}
